import Link from "next/link";
import {headers} from "next/headers";
import {redirect} from "next/navigation";
import {AdminDetailFrame} from "@/components/AdminDetailFrame";
import {getAdminSession} from "@/lib/admin-auth";
import {readAdminStore} from "@/lib/admin-store";
import {getStripeAccountStatus} from "@/lib/stripe";

export const dynamic="force-dynamic";
export default async function StripeDetails(){if(!await getAdminSession())redirect("/admin/login");const [store,stripe,requestHeaders]=await Promise.all([readAdminStore(),getStripeAccountStatus(),headers()]);const origin=process.env.PUBLIC_SITE_ORIGIN||`${requestHeaders.get("x-forwarded-proto")||"https"}://${requestHeaders.get("host")}`;return <AdminDetailFrame section="Payments" title="Stripe" eyebrow="PAYMENT PROVIDER">
  <div className="detail-stat-grid"><article><small>CONNECTION</small><strong className="detail-status">{stripe.account?"Connected":stripe.configured?"Error":"Required"}</strong><span>{stripe.error??"Server-side API key"}</span></article><article><small>MODE</small><strong>{stripe.mode??"—"}</strong><span>Key environment</span></article><article><small>CHARGES</small><strong>{stripe.account?.chargesEnabled?"ON":"OFF"}</strong><span>Stripe account capability</span></article><article><small>STOREFRONT</small><strong>{store.settings.stripeEnabled?"ON":"OFF"}</strong><span>Admin availability switch</span></article></div>
  <div className="detail-layout"><section className="detail-card detail-main"><div className="detail-card-title"><h2>ACCOUNT DETAILS</h2><span>LIVE DIAGNOSTIC</span></div><dl className="stripe-detail-list"><div><dt>Account ID</dt><dd>{stripe.account?.id??"Not connected"}</dd></div><div><dt>Business</dt><dd>{stripe.account?.businessName??"—"}</dd></div><div><dt>Country</dt><dd>{stripe.account?.country??"—"}</dd></div><div><dt>Email</dt><dd>{stripe.account?.email??"—"}</dd></div><div><dt>Details submitted</dt><dd>{stripe.account?.detailsSubmitted?"Yes":"No"}</dd></div><div><dt>Payouts enabled</dt><dd>{stripe.account?.payoutsEnabled?"Yes":"No"}</dd></div><div><dt>Webhook signing secret</dt><dd>{process.env.STRIPE_WEBHOOK_SECRET?"Configured":"Missing"}</dd></div></dl></section><aside className="detail-side"><section className="detail-card"><h2>CONNECT STRIPE</h2><p>Set these encrypted environment variables for Preview and Production in Vercel:</p><code>STRIPE_SECRET_KEY</code><code>STRIPE_WEBHOOK_SECRET</code><p>Webhook URL:</p><code>{origin}/api/v1/webhooks/stripe</code><a className="control-provider-link" href="https://dashboard.stripe.com/apikeys" target="_blank" rel="noreferrer">OPEN STRIPE API KEYS ↗</a><a className="control-provider-link" href="https://dashboard.stripe.com/webhooks" target="_blank" rel="noreferrer">OPEN STRIPE WEBHOOKS ↗</a></section><section className="detail-card"><h2>REQUIRED EVENTS</h2><span>checkout.session.completed</span><span>checkout.session.async_payment_succeeded</span><span>checkout.session.async_payment_failed</span><span>checkout.session.expired</span></section></aside></div>
  <div className="stripe-footer-actions"><Link href="/admin/settings/payments">← ALL PAYMENT PROVIDERS</Link><Link href="/admin?tab=Settings">PAYMENT SETTINGS →</Link></div>
  </AdminDetailFrame>}
