"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import type {AdminSettings} from "@/lib/admin-store";

export function AdminControlCenter({settings,onSave,onReset}:{settings:AdminSettings;onSave:(settings:AdminSettings)=>void;onReset:()=>void}){
  const [value,setValue]=useState(settings);const [section,setSection]=useState("Store");const set=<K extends keyof AdminSettings>(key:K,next:AdminSettings[K])=>setValue(current=>({...current,[key]:next}));
  const sections=["Store","Brand","Homepage","Commerce","Delivery","Payments","AI & features","SEO & social","Admin account"];
  return <section className="admin-module control-center"><div className="admin-toolbar"><div><p>SITE CONFIGURATION</p><h2>FULL CONTROL CENTER</h2></div><span>VERCEL-PERSISTED SETTINGS</span></div><div className="control-shell"><nav>{sections.map(item=><button type="button" className={section===item?"active":""} onClick={()=>setSection(item)} key={item}>{item}</button>)}</nav><form onSubmit={event=>{event.preventDefault();onSave(value)}}>
    {section==="Store"&&<ControlGroup title="Store identity & support" description="The core business details shown across customer service and storefront surfaces."><Text label="Store name" value={value.storeName} onChange={v=>set("storeName",v)}/><Text label="Header wordmark" value={value.wordmark} onChange={v=>set("wordmark",v)}/><Text label="Support email" type="email" value={value.supportEmail} onChange={v=>set("supportEmail",v)}/><Text label="Support phone" value={value.supportPhone} onChange={v=>set("supportPhone",v)}/><Text label="WhatsApp number" value={value.whatsappNumber} onChange={v=>set("whatsappNumber",v)}/><label>Default language<select value={value.defaultLocale} onChange={e=>set("defaultLocale",e.target.value as "en"|"ar")}><option value="en">English</option><option value="ar">Arabic</option></select></label><Toggle label="Maintenance mode" help="Disables normal storefront access when a maintenance screen is connected." value={value.maintenanceMode} onChange={v=>set("maintenanceMode",v)}/></ControlGroup>}
    {section==="Brand"&&<ControlGroup title="Brand system" description="Global colors and naming used by the storefront interface."><Color label="Seasonal accent" value={value.accent} onChange={v=>set("accent",v)}/><Color label="Primary ink" value={value.ink} onChange={v=>set("ink",v)}/><Color label="Warm ivory" value={value.ivory} onChange={v=>set("ivory",v)}/><Text label="Wordmark" value={value.wordmark} onChange={v=>set("wordmark",v)}/></ControlGroup>}
    {section==="Homepage"&&<ControlGroup title="Homepage & announcement" description="Bilingual hero and promotion-bar content."><Text wide label="English announcement" value={value.announcementEn} onChange={v=>set("announcementEn",v)}/><Text wide label="Arabic announcement" value={value.announcementAr} onChange={v=>set("announcementAr",v)}/><Text label="Hero title (English)" value={value.heroTitleEn} onChange={v=>set("heroTitleEn",v)}/><Text label="Hero title (Arabic)" value={value.heroTitleAr} onChange={v=>set("heroTitleAr",v)}/><Text wide label="Hero copy (English)" value={value.heroSubtitleEn} onChange={v=>set("heroSubtitleEn",v)}/><Text wide label="Hero copy (Arabic)" value={value.heroSubtitleAr} onChange={v=>set("heroSubtitleAr",v)}/></ControlGroup>}
    {section==="Commerce"&&<ControlGroup title="Commerce rules" description="Cart, stock, and customer purchasing behavior."><NumberField label="Free delivery threshold (fils)" value={value.freeShippingFils} onChange={v=>set("freeShippingFils",v)}/><NumberField label="Maximum quantity per line" value={value.maxCartQuantity} onChange={v=>set("maxCartQuantity",v)}/><NumberField label="Low-stock threshold" value={value.lowStockThreshold} onChange={v=>set("lowStockThreshold",v)}/><NumberField label="Reservation time (minutes)" min={30} value={value.reservationMinutes} onChange={v=>set("reservationMinutes",v)}/><Toggle label="Guest checkout" value={value.guestCheckoutEnabled} onChange={v=>set("guestCheckoutEnabled",v)}/></ControlGroup>}
    {section==="Delivery"&&<ControlGroup title="Kuwait delivery" description="Prices are stored in fils; 2,000 fils is KWD 2.000."><NumberField label="Standard delivery (fils)" value={value.standardDeliveryFils} onChange={v=>set("standardDeliveryFils",v)}/><NumberField label="Same-day delivery (fils)" value={value.sameDayDeliveryFils} onChange={v=>set("sameDayDeliveryFils",v)}/><Text label="Same-day cutoff" type="time" value={value.sameDayCutoff} onChange={v=>set("sameDayCutoff",v)}/></ControlGroup>}
    {section==="Payments"&&<ControlGroup title="Payment availability" description="Provider secrets stay in encrypted Vercel environment variables and are never stored here."><Toggle label="Stripe Checkout" help="Requires connected Stripe secret and webhook keys." value={value.stripeEnabled} onChange={v=>set("stripeEnabled",v)}/><Toggle label="Stripe promotion codes" value={value.stripeAllowPromotionCodes} onChange={v=>set("stripeAllowPromotionCodes",v)}/><Toggle label="Collect Stripe billing address" value={value.stripeBillingAddress} onChange={v=>set("stripeBillingAddress",v)}/><Text label="Stripe statement name" value={value.stripeStatementDescriptor} onChange={v=>set("stripeStatementDescriptor",v.toUpperCase())}/><Toggle label="MyFatoorah" help="Requires an approved MyFatoorah merchant token." value={value.myFatoorahEnabled} onChange={v=>set("myFatoorahEnabled",v)}/><Toggle label="MyFatoorah cards" value={value.myFatoorahCardEnabled} onChange={v=>set("myFatoorahCardEnabled",v)}/><Toggle label="KNET" value={value.myFatoorahKnetEnabled} onChange={v=>set("myFatoorahKnetEnabled",v)}/><Toggle label="Apple Pay through MyFatoorah" help="Also requires provider enablement and domain verification." value={value.myFatoorahApplePayEnabled} onChange={v=>set("myFatoorahApplePayEnabled",v)}/><Toggle label="Tap Payments" help="Requires TAP_SECRET_KEY and TAP_MERCHANT_ID in Vercel." value={value.tapEnabled} onChange={v=>set("tapEnabled",v)}/><Toggle label="Apple Pay through Tap" help="Requires Tap merchant enablement and Apple domain verification." value={value.tapApplePayEnabled} onChange={v=>set("tapApplePayEnabled",v)}/><Toggle label="Cash on delivery" value={value.codEnabled} onChange={v=>set("codEnabled",v)}/><NumberField label="COD fee (fils)" value={value.codFeeFils} onChange={v=>set("codFeeFils",v)}/><Link className="control-provider-link" href="/admin/settings/payments">OPEN PAYMENT CONNECTIONS →</Link></ControlGroup>}
    {section==="AI & features"&&<><ControlGroup title="Features & automation" description="Control optional storefront experiences without a redeploy."><Toggle label="AI size assistant" value={value.sizeAssistantEnabled} onChange={v=>set("sizeAssistantEnabled",v)}/><Toggle label="Auto-open size assistant" value={value.sizeAssistantAutoOpen} onChange={v=>set("sizeAssistantAutoOpen",v)}/><NumberField label="Assistant delay (milliseconds)" value={value.sizeAssistantDelayMs} onChange={v=>set("sizeAssistantDelayMs",v)}/><Toggle label="Newsletter capture" value={value.newsletterEnabled} onChange={v=>set("newsletterEnabled",v)}/></ControlGroup><OpenAIKeyPanel/></>}
    {section==="SEO & social"&&<ControlGroup title="Search & social presence" description="Bilingual metadata and official social destinations."><Text label="SEO title (English)" value={value.seoTitleEn} onChange={v=>set("seoTitleEn",v)}/><Text label="SEO title (Arabic)" value={value.seoTitleAr} onChange={v=>set("seoTitleAr",v)}/><Text wide label="SEO description (English)" value={value.seoDescriptionEn} onChange={v=>set("seoDescriptionEn",v)}/><Text wide label="SEO description (Arabic)" value={value.seoDescriptionAr} onChange={v=>set("seoDescriptionAr",v)}/><Text label="Instagram URL" type="url" value={value.instagramUrl} onChange={v=>set("instagramUrl",v)}/><Text label="TikTok URL" type="url" value={value.tiktokUrl} onChange={v=>set("tiktokUrl",v)}/></ControlGroup>}
    {section==="Admin account"&&<AdminAccountPanel/>}
    {section!=="Admin account"&&<footer><span>Changes apply to the live data layer after saving.</span><button>SAVE ALL CHANGES</button><button className="danger" type="button" onClick={onReset}>RESET DEMO DATA</button></footer>}
  </form></div></section>
}
function ControlGroup({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <fieldset><legend>{title}</legend><p>{description}</p><div className="control-fields">{children}</div></fieldset>}
function Text({label,value,onChange,type="text",wide=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;wide?:boolean}){return <label className={wide?"wide":""}>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function NumberField({label,value,onChange,min=0}:{label:string;value:number;onChange:(value:number)=>void;min?:number}){return <label>{label}<input type="number" min={min} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label>{label}<span className="control-color"><input type="color" value={value} onChange={e=>onChange(e.target.value)}/><input value={value} onChange={e=>onChange(e.target.value)}/></span></label>}
function Toggle({label,value,onChange,help}:{label:string;value:boolean;onChange:(value:boolean)=>void;help?:string}){return <label className="control-toggle"><span><b>{label}</b>{help&&<small>{help}</small>}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><i/></label>}

export function PaymentModule({settings}:{settings:AdminSettings}){return <section className="admin-module"><div className="admin-toolbar"><div><p>PAYMENT OPERATIONS</p><h2>PAYMENT PROVIDERS</h2></div><Link className="inline-action" href="/admin/settings/payments">CONNECTION CENTER →</Link></div><div className="payment-provider-grid"><Provider name="Stripe" note="Cards · Apple Pay · Link" enabled={settings.stripeEnabled}/><Provider name="MyFatoorah" note="KNET · cards · Apple Pay" enabled={settings.myFatoorahEnabled}/><Provider name="Tap Payments" note="Hosted checkout · Apple Pay" enabled={settings.tapEnabled}/><Provider name="Cash on delivery" note="Kuwait delivery collection" enabled={settings.codEnabled}/></div></section>}
function Provider({name,note,enabled}:{name:string;note:string;enabled:boolean}){return <article><span className={enabled?"provider-dot active":"provider-dot"}/><small>{enabled?"ENABLED":"DISABLED"}</small><h3>{name}</h3><p>{note}</p></article>}

type OpenAIKeyStatus={configured:boolean;source:"admin"|"environment"|"none";lastFour:string|null;updatedAt:string|null};
function OpenAIKeyPanel(){
  const [status,setStatus]=useState<OpenAIKeyStatus|null>(null);const [apiKey,setApiKey]=useState("");const [currentPassword,setCurrentPassword]=useState("");const [message,setMessage]=useState("Loading secure key status…");const [busy,setBusy]=useState(false);
  useEffect(()=>{void fetch("/api/v1/admin/openai-key").then(async response=>{const payload=await response.json() as {data?:OpenAIKeyStatus;message?:string};if(!response.ok)throw new Error(payload.message||"Could not load key status");setStatus(payload.data!);setMessage("")}).catch(reason=>setMessage(reason instanceof Error?reason.message:"Could not load key status"))},[]);
  async function request(method:"PUT"|"DELETE"){setBusy(true);setMessage("");try{const response=await fetch("/api/v1/admin/openai-key",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(method==="PUT"?{apiKey,currentPassword}:{currentPassword})});const payload=await response.json() as {data?:OpenAIKeyStatus;message?:string;fieldErrors?:Record<string,string[]>};if(!response.ok)throw new Error(payload.message||Object.values(payload.fieldErrors||{}).flat()[0]||"Key update failed");setStatus(payload.data!);setApiKey("");setCurrentPassword("");setMessage(method==="PUT"?"OpenAI API key updated. New sizing requests will use it immediately.":"Admin key override removed. The server environment key will be used when available.")}catch(reason){setMessage(reason instanceof Error?reason.message:"Key update failed")}finally{setBusy(false)}}
  return <ControlGroup title="OpenAI connection" description="Replace the API key used by the sizing assistant. The key is encrypted before storage and its plaintext is never returned to this page."><div className="openai-key-status"><span className={status?.configured?"provider-dot active":"provider-dot"}/><b>{status?.configured?"CONNECTED":"NOT CONNECTED"}</b><small>{status?.configured?`•••• ${status.lastFour} · ${status.source==="admin"?"admin-managed override":"Vercel environment"}`:"Add a key to enable AI language understanding."}</small></div><label>New OpenAI API key<input type="password" autoComplete="new-password" placeholder="sk-proj-••••••••" value={apiKey} onChange={event=>setApiKey(event.target.value)}/></label><label>Current admin password<input type="password" autoComplete="current-password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)}/></label><div className="openai-key-actions"><button type="button" disabled={busy||!apiKey||!currentPassword} onClick={()=>void request("PUT")}>{busy?"UPDATING…":"REPLACE API KEY"}</button>{status?.source==="admin"&&<button className="secondary" type="button" disabled={busy||!currentPassword} onClick={()=>void request("DELETE")}>REMOVE OVERRIDE</button>}{message&&<p role="status">{message}</p>}</div></ControlGroup>
}

function AdminAccountPanel(){
  const [username,setUsername]=useState("");const [email,setEmail]=useState("");const [currentPassword,setCurrentPassword]=useState("");const [newPassword,setNewPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");const [message,setMessage]=useState("Loading account…");const [busy,setBusy]=useState(false);
  useEffect(()=>{void fetch("/api/v1/admin/account").then(async response=>{const payload=await response.json() as {data?:{username:string;email:string};message?:string};if(!response.ok)throw new Error(payload.message||"Could not load account");setUsername(payload.data!.username);setEmail(payload.data!.email);setMessage("")}).catch(reason=>setMessage(reason instanceof Error?reason.message:"Could not load account"))},[]);
  async function update(){if(newPassword!==confirmPassword){setMessage("New passwords do not match");return}setBusy(true);setMessage("");try{const response=await fetch("/api/v1/admin/account",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,email,currentPassword,newPassword})});const payload=await response.json() as {data?:{username:string;email:string};message?:string;fieldErrors?:Record<string,string[]>};if(!response.ok)throw new Error(payload.message||Object.values(payload.fieldErrors||{}).flat()[0]||"Update failed");setUsername(payload.data!.username);setEmail(payload.data!.email);setCurrentPassword("");setNewPassword("");setConfirmPassword("");setMessage("Administrator credentials updated. Use the new username or email next time you sign in.")}catch(reason){setMessage(reason instanceof Error?reason.message:"Update failed")}finally{setBusy(false)}}
  return <ControlGroup title="Administrator credentials" description="Change the username, sign-in email, or password. The current password is required to authorize every update."><Text label="Admin username" value={username} onChange={setUsername}/><Text label="Sign-in email" type="email" value={email} onChange={setEmail}/><Text label="Current password" type="password" value={currentPassword} onChange={setCurrentPassword}/><Text label="New password (optional)" type="password" value={newPassword} onChange={setNewPassword}/><Text label="Confirm new password" type="password" value={confirmPassword} onChange={setConfirmPassword}/><div className="admin-account-actions"><small>New passwords require 12+ characters with uppercase, lowercase, number, and symbol.</small><button type="button" disabled={busy||!currentPassword} onClick={()=>void update()}>{busy?"UPDATING…":"UPDATE ADMIN LOGIN"}</button>{message&&<p role="status">{message}</p>}</div></ControlGroup>
}
