'use client';

import {useState} from 'react';
import type {AdminContent,AdminSettings,HomepageDesign,ManagedProduct,WebsiteDesign} from '@/lib/admin-store';

type Section='hero'|'new-in'|'story'|'categories';
export function VisualSiteEditor({settings,products,content,busy,onSave,onOpenProducts,onOpenContent}:{settings:AdminSettings;products:ManagedProduct[];content:AdminContent[];busy:boolean;onSave:(settings:AdminSettings)=>Promise<unknown>;onOpenProducts:()=>void;onOpenContent:()=>void}){
  const [value,setValue]=useState(settings);const [selected,setSelected]=useState<Section>('hero');const [previewPath,setPreviewPath]=useState('/en');const [viewport,setViewport]=useState<'desktop'|'tablet'|'mobile'>('desktop');const design=value.homepageDesign;const site=value.websiteDesign;
  const setDesign=(patch:Partial<HomepageDesign>)=>setValue(current=>({...current,homepageDesign:{...current.homepageDesign,...patch}}));
  const setSite=(patch:Partial<WebsiteDesign>)=>setValue(current=>({...current,websiteDesign:{...current.websiteDesign,...patch}}));
  async function upload(file:File,target:'heroImage'|'storyImage'){const body=new FormData();body.append('file',file);const response=await fetch('/api/v1/admin/media',{method:'POST',body});const payload=await response.json() as {data?:{url:string};message?:string};if(!response.ok||!payload.data)throw new Error(payload.message||'Upload failed');setDesign({[target]:payload.data.url})}
  const heroStyle={backgroundImage:`linear-gradient(rgba(0,0,0,${design.heroOverlay/100}),rgba(0,0,0,${design.heroOverlay/100})),url(${design.heroImage||'/images/giant-hero.jpg'})`,backgroundPosition:design.heroImagePosition,color:design.heroTextColor,fontFamily:design.displayFont};
  return <section className="admin-module visual-editor">
    <div className="admin-toolbar"><div><p>LIVE DESIGN</p><h2>WEBSITE EDITOR</h2></div><button className="primary" disabled={busy} onClick={()=>void onSave(value)}>PUBLISH WEBSITE</button></div>
    <div className="page-editor-nav"><label>PAGE TO PREVIEW<select value={previewPath} onChange={e=>setPreviewPath(e.target.value)}><option value="/en">Homepage</option><option value="/en/category/new-arrivals">New arrivals</option><option value="/en/category/women">Women catalog</option><option value="/en/category/men">Men catalog</option>{products.slice(0,12).map(product=><option key={product.id} value={`/en/product/${product.slug}`}>Product · {product.name}</option>)}{content.map(page=><option key={page.id} value={`/en/pages/${page.slug}`}>Page · {page.titleEn}</option>)}</select></label><div>{(['desktop','tablet','mobile'] as const).map(size=><button key={size} className={viewport===size?'active':''} onClick={()=>setViewport(size)}>{size.toUpperCase()}</button>)}</div><a href={previewPath} target="_blank">OPEN PAGE ↗</a></div>
    <div className={`live-page-frame frame-${viewport}`}><iframe key={`${previewPath}-${storeKey(value)}`} src={previewPath} title="Live storefront preview"/></div>
    <details className="sitewide-controls" open><summary>SITE-WIDE DESIGN CONTROLS</summary><div>
      <fieldset><legend>GLOBAL LAYOUT & COLOR</legend><Range label="Maximum page width" value={site.pageMaxWidth} min={960} max={2560} suffix="px" onChange={pageMaxWidth=>setSite({pageMaxWidth})}/><Range label="Section spacing" value={site.sectionSpacing} min={24} max={180} suffix="px" onChange={sectionSpacing=>setSite({sectionSpacing})}/><Color label="Page background" value={site.bodyBackground} onChange={bodyBackground=>setSite({bodyBackground})}/><Color label="Page text" value={site.bodyTextColor} onChange={bodyTextColor=>setSite({bodyTextColor})}/><Color label="Brand accent" value={value.accent} onChange={accent=>setValue({...value,accent})}/><Range label="Button corners" value={site.buttonRadius} min={0} max={40} suffix="px" onChange={buttonRadius=>setSite({buttonRadius})}/></fieldset>
      <fieldset><legend>HEADER & ANNOUNCEMENT</legend><Range label="Header height" value={site.headerHeight} min={56} max={140} suffix="px" onChange={headerHeight=>setSite({headerHeight})}/><Color label="Header background" value={site.headerBackground} onChange={headerBackground=>setSite({headerBackground})}/><Color label="Header text" value={site.headerTextColor} onChange={headerTextColor=>setSite({headerTextColor})}/><Color label="Announcement background" value={site.announcementBackground} onChange={announcementBackground=>setSite({announcementBackground})}/><Color label="Announcement text" value={site.announcementTextColor} onChange={announcementTextColor=>setSite({announcementTextColor})}/><label>Announcement EN<input value={value.announcementEn} onChange={e=>setValue({...value,announcementEn:e.target.value})}/></label><label>Announcement AR<input dir="rtl" value={value.announcementAr} onChange={e=>setValue({...value,announcementAr:e.target.value})}/></label></fieldset>
      <fieldset><legend>CATALOG & PRODUCT CARDS</legend><Color label="Catalog hero background" value={site.catalogHeroBackground} onChange={catalogHeroBackground=>setSite({catalogHeroBackground})}/><Color label="Catalog hero text" value={site.catalogHeroTextColor} onChange={catalogHeroTextColor=>setSite({catalogHeroTextColor})}/><Range label="Catalog hero height" value={site.catalogHeroHeight} min={160} max={600} suffix="px" onChange={catalogHeroHeight=>setSite({catalogHeroHeight})}/><label>Tagline EN<input value={site.catalogTaglineEn} onChange={e=>setSite({catalogTaglineEn:e.target.value})}/></label><label>Tagline AR<input dir="rtl" value={site.catalogTaglineAr} onChange={e=>setSite({catalogTaglineAr:e.target.value})}/></label><label>Image ratio<select value={site.productImageRatio} onChange={e=>setSite({productImageRatio:e.target.value as WebsiteDesign['productImageRatio']})}><option value="portrait">Portrait</option><option value="square">Square</option><option value="tall">Tall editorial</option></select></label><Range label="Card corners" value={site.cardRadius} min={0} max={60} suffix="px" onChange={cardRadius=>setSite({cardRadius})}/><button type="button" onClick={onOpenProducts}>EDIT PRODUCT TEXT & MEDIA →</button></fieldset>
      <fieldset><legend>PRODUCT PAGE</legend><Range label="Gallery height" value={site.pdpGalleryHeight} min={360} max={1200} suffix="px" onChange={pdpGalleryHeight=>setSite({pdpGalleryHeight})}/><Range label="Product title size" value={site.pdpTitleSize} min={32} max={120} suffix="px" onChange={pdpTitleSize=>setSite({pdpTitleSize})}/><Color label="Information background" value={site.pdpInfoBackground} onChange={pdpInfoBackground=>setSite({pdpInfoBackground})}/><p>Product names, bilingual descriptions, prices, colors, images and sizing assignments are managed per item.</p><button type="button" onClick={onOpenProducts}>OPEN PRODUCT EDITOR →</button></fieldset>
      <fieldset><legend>FOOTER & CONTENT PAGES</legend><Color label="Footer background" value={site.footerBackground} onChange={footerBackground=>setSite({footerBackground})}/><Color label="Footer text" value={site.footerTextColor} onChange={footerTextColor=>setSite({footerTextColor})}/><label>Footer title EN<input value={site.footerTitleEn} onChange={e=>setSite({footerTitleEn:e.target.value})}/></label><label>Footer title AR<input dir="rtl" value={site.footerTitleAr} onChange={e=>setSite({footerTitleAr:e.target.value})}/></label><label>Footer note EN<textarea value={site.footerNoteEn} onChange={e=>setSite({footerNoteEn:e.target.value})}/></label><label>Footer note AR<textarea dir="rtl" value={site.footerNoteAr} onChange={e=>setSite({footerNoteAr:e.target.value})}/></label><button type="button" onClick={onOpenContent}>EDIT CONTENT PAGES →</button></fieldset>
    </div></details>
    <h3 className="homepage-editor-title">HOMEPAGE SECTION EDITOR</h3><div className="visual-editor-layout"><div className="site-preview" aria-label="Homepage visual preview">
      <button className={`preview-hero shape-${design.heroShape} ${selected==='hero'?'selected':''}`} style={heroStyle} onClick={()=>setSelected('hero')}><small>{design.heroEyebrowEn}</small><strong style={{fontSize:`clamp(28px,5vw,${design.heroHeadingSize}px)`}}>{value.heroTitleEn}</strong><span>{value.heroSubtitleEn}</span></button>
      <button className={`preview-new ${selected==='new-in'?'selected':''}`} onClick={()=>setSelected('new-in')}><small>{design.newInEyebrowEn}</small><strong>{design.newInTitleEn}</strong><span>PRODUCT GRID PREVIEW</span></button>
      <button className={`preview-story shape-${design.storyShape} ${selected==='story'?'selected':''}`} style={{color:design.storyTextColor,fontFamily:design.displayFont,backgroundImage:design.storyImage?`linear-gradient(#0008,#0008),url(${design.storyImage})`:undefined,backgroundPosition:design.storyImagePosition}} onClick={()=>setSelected('story')}><small>{design.storyCodeEn}</small><strong style={{fontSize:`clamp(24px,4vw,${design.storyHeadingSize}px)`}}>{design.storyTitleEn}</strong><span>{design.storyBodyEn}</span></button>
      <button className={`preview-categories ${selected==='categories'?'selected':''}`} onClick={()=>setSelected('categories')}><strong>{design.womenLabelEn}</strong><strong>{design.menLabelEn}</strong><strong>{design.accessoriesLabelEn}</strong></button>
    </div><div className="visual-controls">
      <div className="editor-section-tabs">{(['hero','new-in','story','categories'] as Section[]).map(item=><button className={selected===item?'active':''} key={item} onClick={()=>setSelected(item)}>{item.toUpperCase()}</button>)}</div>
      <fieldset><legend>GLOBAL TYPOGRAPHY</legend><label>Heading font<select value={design.displayFont} onChange={event=>setDesign({displayFont:event.target.value as HomepageDesign['displayFont']})}>{['Space Grotesk','Inter','Arial','Georgia'].map(item=><option key={item}>{item}</option>)}</select></label><label>Body font<select value={design.bodyFont} onChange={event=>setDesign({bodyFont:event.target.value as HomepageDesign['bodyFont']})}>{['Inter','Arial','Georgia'].map(item=><option key={item}>{item}</option>)}</select></label></fieldset>
      {selected==='hero'&&<><fieldset><legend>HERO TEXT</legend><label>Eyebrow EN<input value={design.heroEyebrowEn} onChange={event=>setDesign({heroEyebrowEn:event.target.value})}/></label><label>Eyebrow AR<input dir="rtl" value={design.heroEyebrowAr} onChange={event=>setDesign({heroEyebrowAr:event.target.value})}/></label><label>Title EN<input value={value.heroTitleEn} onChange={event=>setValue({...value,heroTitleEn:event.target.value})}/></label><label>Title AR<input dir="rtl" value={value.heroTitleAr} onChange={event=>setValue({...value,heroTitleAr:event.target.value})}/></label><label>Subtitle EN<textarea value={value.heroSubtitleEn} onChange={event=>setValue({...value,heroSubtitleEn:event.target.value})}/></label><label>Subtitle AR<textarea dir="rtl" value={value.heroSubtitleAr} onChange={event=>setValue({...value,heroSubtitleAr:event.target.value})}/></label></fieldset><MediaControls image={design.heroImage} shape={design.heroShape} position={design.heroImagePosition} minHeight={design.heroMinHeight} headingSize={design.heroHeadingSize} color={design.heroTextColor} overlay={design.heroOverlay} onUpload={file=>upload(file,'heroImage')} onChange={patch=>setDesign(patch as Partial<HomepageDesign>)} prefix="hero"/></>}
      {selected==='new-in'&&<fieldset><legend>NEW IN SECTION</legend><label>Eyebrow EN<input value={design.newInEyebrowEn} onChange={e=>setDesign({newInEyebrowEn:e.target.value})}/></label><label>Eyebrow AR<input dir="rtl" value={design.newInEyebrowAr} onChange={e=>setDesign({newInEyebrowAr:e.target.value})}/></label><label>Heading EN<input value={design.newInTitleEn} onChange={e=>setDesign({newInTitleEn:e.target.value})}/></label><label>Heading AR<input dir="rtl" value={design.newInTitleAr} onChange={e=>setDesign({newInTitleAr:e.target.value})}/></label></fieldset>}
      {selected==='story'&&<><fieldset><legend>STORY TEXT</legend>{(['storyCode','storyTitle','storyBody'] as const).flatMap(key=>['En','Ar'].map(language=>{const field=`${key}${language}` as keyof HomepageDesign;return <label key={field}>{key.replace('story','')} {language}<textarea dir={language==='Ar'?'rtl':'ltr'} value={String(design[field])} onChange={e=>setDesign({[field]:e.target.value})}/></label>}))}</fieldset><MediaControls image={design.storyImage} shape={design.storyShape} position={design.storyImagePosition} minHeight={design.storyMinHeight} headingSize={design.storyHeadingSize} color={design.storyTextColor} onUpload={file=>upload(file,'storyImage')} onChange={patch=>setDesign(patch as Partial<HomepageDesign>)} prefix="story"/></>}
      {selected==='categories'&&<fieldset><legend>CATEGORY LABELS</legend>{(['women','men','accessories'] as const).flatMap(name=>['En','Ar'].map(language=>{const field=`${name}Label${language}` as keyof HomepageDesign;return <label key={field}>{name} {language}<input dir={language==='Ar'?'rtl':'ltr'} value={String(design[field])} onChange={e=>setDesign({[field]:e.target.value})}/></label>}))}</fieldset>}
    </div></div>
  </section>;
}

function storeKey(value:AdminSettings){return `${value.accent}-${value.websiteDesign.headerHeight}-${value.websiteDesign.cardRadius}`}
function Range({label,value,min,max,suffix,onChange}:{label:string;value:number;min:number;max:number;suffix:string;onChange:(value:number)=>void}){return <label>{label} <b>{value}{suffix}</b><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label>{label}<span className="color-control"><input type="color" value={value} onChange={e=>onChange(e.target.value)}/><input value={value} onChange={e=>onChange(e.target.value)}/></span></label>}

function MediaControls({image,shape,position,minHeight,headingSize,color,overlay,onUpload,onChange,prefix}:{image:string;shape:string;position:string;minHeight:number;headingSize:number;color:string;overlay?:number;onUpload:(file:File)=>Promise<void>;onChange:(patch:Record<string,unknown>)=>void;prefix:'hero'|'story'}){return <fieldset><legend>IMAGE & DIMENSIONS</legend><label>Image URL<input value={image} onChange={e=>onChange({[`${prefix}Image`]:e.target.value})}/></label><label>Or upload<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>{const file=e.target.files?.[0];if(file)void onUpload(file)}}/></label><label>Crop position<select value={position} onChange={e=>onChange({[`${prefix}ImagePosition`]:e.target.value})}><option>center</option><option>top</option><option>bottom</option><option>left</option><option>right</option></select></label><label>Shape<select value={shape} onChange={e=>onChange({[`${prefix}Shape`]:e.target.value})}>{prefix==='hero'&&<option>arc</option>}<option>rounded</option><option>square</option>{prefix==='story'&&<option>circle</option>}</select></label><label>Section height <b>{minHeight}px</b><input type="range" min="360" max="1200" step="10" value={minHeight} onChange={e=>onChange({[`${prefix}MinHeight`]:Number(e.target.value)})}/></label><label>Heading size <b>{headingSize}px</b><input type="range" min="32" max="160" value={headingSize} onChange={e=>onChange({[`${prefix}HeadingSize`]:Number(e.target.value)})}/></label><label>Text color<input type="color" value={color} onChange={e=>onChange({[`${prefix}TextColor`]:e.target.value})}/></label>{overlay!==undefined&&<label>Image overlay <b>{overlay}%</b><input type="range" min="0" max="80" value={overlay} onChange={e=>onChange({heroOverlay:Number(e.target.value)})}/></label>}</fieldset>}
