export type Locale='en'|'ar';
export type ProductBundle={id:string;label:string;quantity:number;price:number};
export type Product={id:string;slug:string;name:string;nameAr:string;category:'women'|'men'|'accessories';fit:string;color:string;price:number;compareAt?:number;image:string;images?:string[];imageAlt:string;sizes:string[];bundles?:ProductBundle[];badge?:string;description:string;sizeGuideId:string;fitProfile:'compression'|'sculpt'|'regular'|'relaxed'|'oversized'|'one-size';stretchLevel:'none'|'low'|'medium'|'high';heightRule:'alpha-size'|'length-only'|'none'};
const images=[
'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1571731956672-f2b94d7dd0cb?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1517963879433-6ad2b056d712?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1548690312-e3b507d8c110?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1526401485004-2aa7d4cfa85b?auto=format&fit=crop&w=1000&q=85'];
const bases=[['Axis Training Tee','تي شيرت أكسيس','men','Oversized fit',18000],['Form Seamless Set','طقم فورم','women','Sculpt fit',32000],['Orbit Studio Bra','حمالة أوربت','women','Medium support',16500],['Core Lift Short','شورت كور ليفت','men','Regular fit',14000],['Arc Legging','ليقنز آرك','women','Body fit',22500],['Summit Hoodie','هودي ساميت','men','Relaxed fit',29000],['Vector Tank','فانيلة فيكتور','men','Muscle fit',12000],['Motion Flare','موشن فلير','women','Body fit',26000],['G-Ring Cap','قبعة جي رينغ','accessories','One size',9500],['Foundation Jogger','بنطال فاونديشن','men','Tapered fit',22000],['Pulse Crop','بلوزة بالس','women','Body fit',15500],['Transit Duffel','حقيبة ترانزيت','accessories','32 litre',24000]] as const;
const colors=['Black','Burnt Orange','Ivory'];
const guideMeta:Record<string,{id:string;fit:Product['fitProfile'];stretch:Product['stretchLevel'];height:Product['heightRule']}>=
{'Axis Training Tee':{id:'unisex-oversized',fit:'oversized',stretch:'low',height:'none'},'Form Seamless Set':{id:'women-bottoms',fit:'sculpt',stretch:'high',height:'length-only'},'Orbit Studio Bra':{id:'sports-bra',fit:'compression',stretch:'high',height:'none'},'Core Lift Short':{id:'men-bottoms',fit:'regular',stretch:'medium',height:'length-only'},'Arc Legging':{id:'women-bottoms',fit:'sculpt',stretch:'high',height:'length-only'},'Summit Hoodie':{id:'unisex-oversized',fit:'oversized',stretch:'low',height:'none'},'Vector Tank':{id:'men-tops',fit:'regular',stretch:'medium',height:'none'},'Motion Flare':{id:'women-bottoms',fit:'sculpt',stretch:'high',height:'length-only'},'G-Ring Cap':{id:'one-size',fit:'one-size',stretch:'none',height:'none'},'Foundation Jogger':{id:'men-bottoms',fit:'regular',stretch:'medium',height:'length-only'},'Pulse Crop':{id:'women-tops',fit:'regular',stretch:'medium',height:'none'},'Transit Duffel':{id:'one-size',fit:'one-size',stretch:'none',height:'none'}};
export const products:Product[]=Array.from({length:36},(_,i)=>{const b=bases[i%12];const color=colors[Math.floor(i/12)];const meta=guideMeta[b[0]];const image=images[i%12];return{id:`P${String(i+1).padStart(3,'0')}`,slug:`${b[0].toLowerCase().replaceAll(' ','-')}-${color.toLowerCase().replaceAll(' ','-')}`,name:b[0],nameAr:b[1],category:b[2],fit:b[3],color,price:b[4]+Math.floor(i/12)*1000,compareAt:i%7===0?b[4]+5000:undefined,image,images:[image],imageAlt:`GIANT ${b[0]} in ${color}`,sizes:b[2]==='accessories'?['ONE SIZE']:['XS','S','M','L','XL','XXL'],bundles:[],badge:i<8?'NEW':i%9===0?'EXCLUSIVE':undefined,description:'A high-performance essential built with breathable stretch fabric, clean bonded details and a confident everyday silhouette.',sizeGuideId:meta.id,fitProfile:meta.fit,stretchLevel:meta.stretch,heightRule:meta.height}});
export const categories=[{slug:'women',en:'Women',ar:'نساء'},{slug:'men',en:'Men',ar:'رجال'},{slug:'accessories',en:'Accessories',ar:'إكسسوارات'},{slug:'new-arrivals',en:'New Arrivals',ar:'وصل حديثاً'},{slug:'sale',en:'Sale',ar:'تخفيضات'}];
export const money=(fils:number,locale:Locale='en')=>new Intl.NumberFormat(locale==='ar'?'ar-KW':'en-KW',{style:'currency',currency:'KWD',minimumFractionDigits:3}).format(fils/1000);
export function bundleForQuantity(product:Pick<Product,'bundles'>,quantity:number){return product.bundles?.filter(bundle=>bundle.quantity===quantity&&bundle.price>=0).sort((a,b)=>a.price-b.price)[0]}
export function productLineTotal(product:Pick<Product,'price'|'bundles'>,quantity:number){return bundleForQuantity(product,quantity)?.price??product.price*quantity}
