import PDFDocument from 'pdfkit';
import {NextRequest,NextResponse} from 'next/server';
import {getAdminSession} from '@/lib/admin-auth';
import {readAdminStore,type AdminOrder} from '@/lib/admin-store';
import {filterOrdersByRange,isCompletedPurchase,orderCost,type ReceiptRange} from '@/lib/commerce-analytics';

export const runtime='nodejs';
const ranges=new Set<ReceiptRange>(['today','yesterday','7d','30d','year','all']);
const money=(fils:number)=>`KWD ${(fils/1000).toFixed(3)}`;
type Store=Awaited<ReturnType<typeof readAdminStore>>;

function collect(doc:PDFKit.PDFDocument,draw:()=>void){return new Promise<Buffer>((resolve,reject)=>{const chunks:Buffer[]=[];doc.on('data',(chunk:Buffer)=>chunks.push(chunk));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));draw();doc.end()})}
function brandHeader(doc:PDFKit.PDFDocument,label:string){doc.font('Courier').fontSize(16).text('GIANT KUWAIT',{align:'center'}).fontSize(9).text(label,{align:'center'}).moveDown(.5);doc.moveTo(34,doc.y).lineTo(561,doc.y).stroke();doc.moveDown(.7)}
function totals(doc:PDFKit.PDFDocument,rows:Array<[string,number]>){doc.moveDown().moveTo(34,doc.y).lineTo(561,doc.y).stroke().moveDown(.6);for(const[label,value]of rows){const y=doc.y;doc.fontSize(9).text(label,335,y,{width:115}).text(money(value),455,y,{width:105,align:'right'});doc.y=y+11}}

async function renderCombinedPdf(orders:AdminOrder[],range:string,store:Store){const doc=new PDFDocument({size:'A4',margin:34,info:{Title:`GIANT sales receipt - ${range}`}});return collect(doc,()=>{brandHeader(doc,'SALES RECEIPT');doc.fontSize(8).text(`Period: ${range.toUpperCase()}`).text(`Generated: ${new Date().toLocaleString('en-KW')}`).text(`Orders: ${orders.length}`).moveDown();if(orders.length===1){const order=orders[0];doc.fontSize(9).text(`Order: ${order.number}`).text(`Customer: ${order.customer}`).text(`Placed: ${new Date(order.createdAt).toLocaleString('en-KW')}`).text(`Payment: ${(order.payment||'legacy').toUpperCase()} / ${(order.paymentStatus||'unknown').toUpperCase()}`).moveDown()}
  const items=new Map<string,{name:string;sku:string;quantity:number;sales:number;cost:number}>();for(const order of orders){for(const line of order.lines||[]){const key=`${line.sku}-${line.size||''}`;const current=items.get(key)||{name:`${line.name}${line.size?` / ${line.size}`:''}`,sku:line.sku,quantity:0,sales:0,cost:0};current.quantity+=line.quantity;current.sales+=line.lineTotal??line.unitPrice*line.quantity;current.cost+=(line.unitCost??store.products.find(product=>product.id===line.productId)?.cost??Math.round(line.unitPrice*.44))*line.quantity;items.set(key,current)}}
  const tableHeader=()=>{const y=doc.y;doc.fontSize(8).text('ITEM',34,y,{width:255}).text('QTY',300,y,{width:45,align:'right'}).text('SALES',355,y,{width:95,align:'right'}).text('COST',460,y,{width:100,align:'right'});doc.y=y+12;doc.moveTo(34,doc.y).lineTo(561,doc.y).stroke();doc.moveDown(.5)};tableHeader();for(const item of items.values()){if(doc.y>735){doc.addPage();tableHeader()}const y=doc.y;doc.fontSize(8).text(`${item.name}\n${item.sku}`,34,y,{width:255}).text(String(item.quantity),300,y,{width:45,align:'right'}).text(money(item.sales),355,y,{width:95,align:'right'}).text(money(item.cost),460,y,{width:100,align:'right'});doc.y=Math.max(doc.y,y+25)}if(!items.size)doc.text('No captured line items in this period.');const subtotal=orders.reduce((sum,order)=>sum+(order.subtotal??order.total),0);const discounts=orders.reduce((sum,order)=>sum+(order.discount??0),0);const delivery=orders.reduce((sum,order)=>sum+(order.delivery??0),0);const net=orders.reduce((sum,order)=>sum+order.total,0);const cost=orders.reduce((sum,order)=>sum+orderCost(order,store.products),0);totals(doc,[['SUBTOTAL',subtotal],['DISCOUNTS',-discounts],['DELIVERY',delivery],['NET SALES',net],['ITEM COST',cost],['EST. PROFIT',net-delivery-cost]]);doc.moveDown(1.5).fontSize(7).text('Internal operations receipt. Monochrome layout optimized for low-cost printing.',{align:'center'})})}

function drawIndividual(doc:PDFKit.PDFDocument,order:AdminOrder,index:number,total:number){brandHeader(doc,'ORDER RECEIPT');doc.fontSize(8).text(`Receipt ${index+1} of ${total}`).text(`Order: ${order.number}`).text(`Placed: ${new Date(order.createdAt).toLocaleString('en-KW')}`).text(`Customer: ${order.customer}`).text(`Email: ${order.email}`).text(`Mobile: ${order.mobile||'—'}`).text(`Payment: ${(order.payment||'legacy').toUpperCase()} / ${(order.paymentStatus||'unknown').toUpperCase()}`).moveDown();if(order.address)doc.text(`Delivery: ${order.address.area}, Block ${order.address.block}, ${order.address.street}, Building ${order.address.building}${order.address.floor?`, Floor ${order.address.floor}`:''}`).moveDown();const y=doc.y;doc.fontSize(8).text('ITEM',34,y,{width:300}).text('QTY',345,y,{width:45,align:'right'}).text('PRICE',405,y,{width:70,align:'right'}).text('TOTAL',490,y,{width:70,align:'right'});doc.y=y+12;doc.moveTo(34,doc.y).lineTo(561,doc.y).stroke();doc.moveDown(.5);for(const line of order.lines||[]){const rowY=doc.y;doc.text(`${line.name}${line.size?` / ${line.size}`:''}${line.bundleLabel?` · ${line.bundleLabel}`:''}\n${line.sku} · ${line.color}`,34,rowY,{width:300}).text(String(line.quantity),345,rowY,{width:45,align:'right'}).text(money(line.unitPrice),405,rowY,{width:70,align:'right'}).text(money(line.lineTotal??line.unitPrice*line.quantity),490,rowY,{width:70,align:'right'});doc.y=Math.max(doc.y,rowY+25)}if(!order.lines?.length)doc.text('No captured line items.');totals(doc,[['SUBTOTAL',order.subtotal??order.total],['DISCOUNT',-(order.discount??0)],['DELIVERY',order.delivery??0],['TOTAL',order.total]]);doc.moveDown(1.5).fontSize(7).text('Thank you for shopping with GIANT Kuwait. Keep this receipt for your records.',{align:'center'})}
async function renderIndividualPdf(orders:AdminOrder[]){const doc=new PDFDocument({size:'A4',margin:34,autoFirstPage:false,info:{Title:`GIANT individual receipts - ${orders.length}`}});return collect(doc,()=>{orders.forEach((order,index)=>{doc.addPage();drawIndividual(doc,order,index,orders.length)})})}

export async function GET(request:NextRequest){if(!await getAdminSession())return NextResponse.json({code:'UNAUTHORIZED',message:'Sign in required'},{status:401});const store=await readAdminStore();const orderId=request.nextUrl.searchParams.get('orderId');const requestedIds=(request.nextUrl.searchParams.get('orderIds')||'').split(',').filter(Boolean);const rangeParam=(request.nextUrl.searchParams.get('range')||'today') as ReceiptRange;const layout=request.nextUrl.searchParams.get('layout')==='individual'?'individual':'combined';if(requestedIds.length>100)return NextResponse.json({code:'TOO_MANY_RECEIPTS',message:'Select up to 100 receipts at a time.'},{status:400});if(!orderId&&!requestedIds.length&&!ranges.has(rangeParam))return NextResponse.json({code:'INVALID_RANGE'},{status:400});const allowedIds=new Set(requestedIds);const orders=orderId?store.orders.filter(order=>order.id===orderId):requestedIds.length?store.orders.filter(order=>allowedIds.has(order.id)&&isCompletedPurchase(order)):filterOrdersByRange(store.orders,rangeParam).filter(isCompletedPurchase);if((orderId||requestedIds.length)&&!orders.length)return NextResponse.json({code:'ORDER_NOT_FOUND'},{status:404});const label=orderId?orders[0].number:requestedIds.length?`selected-${orders.length}`:rangeParam;const pdf=layout==='individual'?await renderIndividualPdf(orders):await renderCombinedPdf(orders,label,store);const suffix=layout==='individual'?'-individual':'';return new NextResponse(new Uint8Array(pdf),{headers:{'Content-Type':'application/pdf','Content-Disposition':`inline; filename="giant-receipt-${label}${suffix}.pdf"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}})}
